# Generated by Django 2.2.2 on 2019-07-29 08:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titile', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateTimeField(blank=True, null=True)),
                ('qualification', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('experience', models.CharField(max_length=2)),
                ('contact', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=50)),
                ('course_type', models.CharField(max_length=2)),
                ('expected_date', models.DateTimeField(blank=True, null=True)),
                ('follow_up', models.TextField(blank=True, null=True)),
                ('lead_sourse', models.CharField(max_length=100)),
                ('lead_date', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enquiry.Course')),
            ],
        ),
    ]
