# Generated by Django 2.2.2 on 2019-07-29 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='titile',
            new_name='title',
        ),
    ]
