# Generated by Django 2.2.2 on 2019-07-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0002_auto_20190729_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
