# Generated by Django 2.2.2 on 2019-07-29 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0004_enquiry_counsellor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='counsellor',
            field=models.ForeignKey(limit_choices_to={'role': '2'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
