# Generated by Django 2.2.2 on 2019-07-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0006_enquiry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='gender',
            field=models.CharField(default=0, max_length=1),
            preserve_default=False,
        ),
    ]
