# Generated by Django 2.2.2 on 2019-08-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0010_center_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='lead_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
