# Generated by Django 2.2.2 on 2019-08-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0011_auto_20190801_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow_ups',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
