# Generated by Django 2.2.2 on 2019-08-05 08:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0013_auto_20190805_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='course_fee',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('amount', models.CharField(blank=True, max_length=7, null=True)),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('enquiry_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enquiry.Enquiry')),
            ],
        ),
    ]
