# Generated by Django 2.2.2 on 2019-08-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0014_auto_20190805_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='course_fee',
            field=models.CharField(blank=True, default=0, max_length=7, null=True),
        ),
    ]
