# Generated by Django 2.2.2 on 2019-08-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0015_auto_20190805_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='lms_id',
            field=models.CharField(default=0, max_length=2),
        ),
    ]
