# Generated by Django 2.2.2 on 2019-08-08 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0017_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='starting_date',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='batch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='enquiry.Batch'),
            preserve_default=False,
        ),
    ]
