# Generated by Django 2.2.2 on 2019-08-08 10:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0018_auto_20190808_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='class_end',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Conversation Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batch',
            name='class_start',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Conversation Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batch',
            name='days',
            field=models.CharField(choices=[('0', 'Weekdays'), ('1', 'Weekends')], default='0', max_length=2),
        ),
    ]
