# Generated by Django 2.2.2 on 2019-08-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0019_auto_20190808_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='class_end',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='class_start',
            field=models.TimeField(blank=True),
        ),
    ]
