# Generated by Django 2.2.2 on 2019-08-08 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0020_auto_20190808_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enquiry.Batch'),
        ),
    ]
