# Generated by Django 2.2.2 on 2019-08-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0022_auto_20190808_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='lms_username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
