# Generated by Django 2.1.5 on 2019-06-10 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
