# Generated by Django 2.2.2 on 2019-07-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190725_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('2', 'Counsellor'), ('3', 'Student')], default='0', max_length=2),
        ),
    ]
