# Generated by Django 2.2.2 on 2019-07-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190726_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='center',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
