# Generated by Django 2.2.2 on 2019-07-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_customuser_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='center',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
