# Generated by Django 2.2.2 on 2019-07-26 11:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20190726_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_login_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
