# Generated by Django 2.2.2 on 2019-07-26 11:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_customuser_last_login_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='last_login_date',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
