# Generated by Django 2.2.2 on 2019-08-05 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20190801_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='select_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enquiry.Center'),
        ),
    ]
