# Generated by Django 2.2.2 on 2019-08-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20190805_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('2', 'Counsellor'), ('3', 'Student'), ('4', 'Trainer')], default='2', max_length=2),
        ),
    ]
